export const REGISTER_URL='/register'
export const VERIFY_OTP='/verify'
export const LOGIN='/login'
export const RESEND='/resend'
export const GOOGLE_AUTH='/google'
export const VERIFY_EMAIL='/verifyemail'
export const FORGOT_PASS='/forgot'
export const EDIT_PROFILE='/editprofile'
export const PROFILE_UPLOAD='/upload'
export const CHANGE_PASS='/changepassword'
export const FECTH_HOSTEL='/fetchhostel'
export const FETCH_ROOM='/fetchroom'
export const PROPERTY_DETAILS='/propertydetails'
export const WISHLIST='/wishlist'
export const FIND_WISH='/findwish'
export const FECTH_WISHLIST='/fetchwish'
export const REMOVE_WISH='/removewish'
export const FETCH_WISH='/wish'
export const FETCH_RESERVATION='/fetchreservation'
export const BOOKING_DETAILS='/bookingdetails'
export const CONTINUE_PAYMENT='/continuepayment'


export const CONNECT_HOST='/connecthost'
export const FETCH_HOST='/fetchhost'
export const FETCH_CONNECT='/fetchconnection'
export const FETCH_USER_MESSAGE='/fetchmessage'

export const NEARME='/nearme'

export const RATING='/rate'

export const FETCH_REVIEW='/fetchreview'
export const FETCH_NOTIFICATIONS='/fetchnotifications'
export const CANCEL_RES='/cancel'