export const HOST_LOGIN='/host/login'
export const HOST_VERIFY='/host/verify'
export const HOST_RESEND='/host/hostresend'
export const HOST_EDIT_PROFILE='/host/hosteditprofile'
export const HOST_UPLOAD_PHOTO='/host/uploadphoto'
export const HOST_CHANGE_PASS='/host/changepass'