export const HOST_LOGIN='/host/login'
export const HOST_VERIFY='/host/verify'
export const HOST_RESEND='/host/hostresend'
export const HOST_EDIT_PROFILE='/host/hosteditprofile'
export const HOST_UPLOAD_PHOTO='/host/uploadphoto'
export const HOST_CHANGE_PASS='/host/changepass'

export const FETCH_AMENITIES='/host/amenities'
export const FETCH_SAFETY='/host/safety'
export const ADD_PROPERTY='/host/addproperty'
export const FETCH_PROPERTY='/host/property'
export const UPDATE_PROPERTY='/host/updateproperty'
export const AVAILABLE='/host/available'
export const FETCH_RESERVATION='/host/fetchreservation'
export const ACTION_RESERVATION='/host/actionreservation'

export const FETCHPAYMENT='/host/fetchpayment'
export const ADDAMOUNT='/host/addamount'
export const VERIFYAMOUNT='/host/verifyamount'